### ISSUE TITLE
Invalid selector for @extend

### ISSUE THREAD

**Issue by jacquesletesson** [emagnier/inuitcss.widths-generator#1] opened 2015-01-28 13:51 UTC
Hi there,

I got a `Invalid selector for @extend` on line 99.

```
$inuit-use-fractions: false;
$inuit-widths: 1, 2, 3, 12;
@import "bower_components/inuit-widths-generator/trumps.widths-generator";
@import "bower_components/inuit-widths-responsive-generator/trumps.widths-responsive-generator";
```

Any idea on what could cause that?

Cheers.

Sass 3.4.9 (Selective Steve)

**Comment by emagnier** [comment] 2015-02-02 04:39
Hi @jacquesletesson, thanks for your message!
However I'm not able to reproduce it on Sass 3.4.9

Here is my test file:

``` scss
@import "bower_components/inuit-defaults/settings.defaults";
@import "bower_components/inuit-responsive-settings/settings.responsive";
@import "bower_components/inuit-responsive-tools/tools.responsive";

$inuit-use-fractions: false;
$inuit-widths: 1, 2, 3, 12;
@import "bower_components/inuit-widths-generator/trumps.widths-generator";
@import "bower_components/inuit-widths-responsive-generator/trumps.widths-responsive-generator";
```

You may have a problem elsewhere with a config variable or dependancy that causes the error.
If you still have the problem, can give me more details or a repro project?

**Comment by jacquesletesson** [comment] 2015-02-03 08:40
Well I removed all the other imports but I still have the issue...

Then I thought that the error was related to the dependencies of `inuitcss.widths-responsive-generator`.

```
"dependencies": { 
"inuit-defaults": "~0.2.1", 
"inuit-responsive-settings": "~0.1.2", 
"inuit-responsive-tools": "~0.1.1", 
"inuit-widths-generator": "~0.3.4"
} 
```

Where in my project I had the latest one... But it didn't fix the problem.

```
  "name": "inuit-responsive-settings",
  "version": "0.1.3",

  "name": "inuit-responsive-tools",
  "version": "0.1.3",
```

Will share a private repo with you. 

Thank you for your time.

Cheers.

**Comment by emagnier** [comment] 2015-07-28 21:07
Since I'm not able to reproduce it I'm closing the issue.
@jacquesletesson feel free to drop a message here if you still have the problem. Thanks!

**Closed as completed by emagnier** 2015-07-28 21:07 UTC
